version: "3.8"

services:
  hub:
    image: selenium/hub:latest
    ports:
      - 4444:4444
  chrome:
    image: selenium/node-chrome:latest
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 1
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1
  firefox:
    image: selenium/node-firefox:latest
    shm_size: '2g'
    depends_on:
      - hub
    deploy:
      replicas: 1
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_MAX_SESSIONS=4
      - SE_VNC_NO_PASSWORD=1
  checkout-test:
    image: landowolf/selenium-java-testng:latest
    depends_on:
      - chrome
    environment:
      - TEST_RUNNER=${TEST_RUNNER}
      - SELENIUM_GRID_ENABLED=${SELENIUM_GRID_ENABLED}
      - GRID_HUB_HOST=${GRID_HUB_HOST}