version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:17-buster-node-browsers
    steps:
      - checkout
      - run:
          name: Run Selenium Tests
          command: |
            chmod +x gradlew
             ./gradlew clean test -Pall_tests

workflows:
  version: 2
  build-test:
    jobs:
      - build